<script>
import {
  afterUpdate
  , onMount
} from 'svelte'
import { deriveGeneratorPassword } from '@util/crypto/kdf'
import { loadDecryptSeed } from '@util/crypto/encryption'
import * as c from '@/constants.js'
import {
  needsSetup
  , disableAnnoyingMobileInputBugs
} from '@util/helper.js'
// derives a password from our params
import deriveSrsPass from '@util/srsPass/generator'
// provides necessities for helping transform generated bytes into a flexible outlined character sets
import {
  charsetDict,
  charsetDefinitions,
  dedupeChars,
  validatePassFormat,
} from '@util/srsPass/charsetter'

const msg = {
  passInput: "Enter password here..."
  , loading:  "Generating..."
}
let unlocking = false
  , generating = false
  , unlockPass = ''
  , salt = ''
  , pass = ""
  , childPass = ""
  , login = ""
  , uri = ""
  , advOpts = false
  , index = 0
  , passLen = 20
  , customAlpha = ''
  , childPassFormatDefault = '*'
  , childPassFormat = childPassFormatDefault
  , unlockPassInputDOM
  , showPass = false

charsetDict.c = customAlpha

onMount(() => unlockPassInputDOM = document.getElementById('unlockPassInput'))

afterUpdate(() => {
  disableAnnoyingMobileInputBugs()
})

function handleUnlockEnter(event) {
  if (event.key === "Enter") {
    event.preventDefault()
    handleUnlockClick()
  }
}

function handleCopyClick() {
  navigator.clipboard.writeText(childPass)
}

function handlePassFormatInput(event) {
  const { key } = event
  if (Object.keys(charsetDict).indexOf(key) < 0)
    return event.preventDefault()
  else if (key === 'c' && customAlpha.length === 0) {
    event.preventDefault()
    return alert(`You must define a custom alphabet in the input underneath, before you can use 'c' in the format!`)
  }
}

async function handleUnlockClick() {
  unlocking = true
  try {
    // add appropriate exceptions and handling thereof
    const saltProm = loadDecryptSeed(unlockPass)
    const passProm = deriveGeneratorPassword(unlockPass)
    unlockPass = ''
    salt = await saltProm
    pass = await passProm
  } catch (e) {
    const errorDict = {
      'Unsupported state or unable to authenticate data': `Incorrect ${c.passTerm.toLowerCase()} entered...`
    }
    const knownError = errorDict[e.message]
    if (knownError)
      alert(knownError)
    else
      console.error(e) || alert('Unhandled Error, check log and report!')
  } finally {
    unlocking = false
  }
}

async function handleGenerateClick() {
  const cpf = childPassFormat
  if (!validatePassFormat(cpf))
    return alert(`Invalid pass format... please check tooltips for valid characters by hovering over the ${childPassTerm} format input`)
  childPass = ""
  generating = true
  // uint8 array
  //let fmt = `${index}${uri}${login}`
  // index is omitted unless non-zero, to keep the salt from being too easily
  // identifiable by such a consistent marker in memory

  childPass = await deriveSrsPass(
    pass,
    salt,
    index,
    uri,
    login,
    passLen,
    cpf
  )
  generating = false
}

const blacklistDecimal = event =>
  event.keyCode === 190 && event.preventDefault()

const isEmpty = x => !x || x.length === 0

$: needsCredentials = isEmpty(pass) || isEmpty(salt)
$: index = Math.floor(index)
$: passLen = Math.floor(passLen)
$: customAlpha = dedupeChars(customAlpha)
$: charsetDict.c = customAlpha
$: if(customAlpha.length === 1 &&
  childPassFormat === childPassFormatDefault) childPassFormat = 'c'
$: unlockPassInputDOM && (
  showPass ? unlockPassInputDOM.setAttribute('type', 'text') : unlockPassInputDOM.setAttribute('type', 'password'))
</script>

<div>
  {#if needsCredentials}
    <h3>Usable offline & as PWA for extra security</h3>
    {#if unlocking}
      <p>Unlocking... please wait</p>
    {:else}
      <div>
        <label for="unlockPassInput" title={c.tipUnlockPass}>Please enter your {@html c.passHtml} to begin!</label>
        <input autofocus={!needsSetup()} id="unlockPassInput" title={c.tipUnlockPass} name="unlockPassInput" type="text" bind:value={unlockPass} disabled={unlocking} on:keypress={handleUnlockEnter}>
        <button title={c.tipUnlockPass} on:click={handleUnlockClick} disabled={unlocking}>
          Unlock
        </button>
        <div class="checkbox">
          <label for=showUnlockPass><span>show password<input name="showUnlockPass" type="checkbox" bind:checked={showPass}></span></label>
        </div>
      </div>
    {/if}
  {:else}
    <p>Note: All inputs are case sensitive, so remember where you use capital or small letters!</p>
    <br/>
    <div class="input-container" title={c.tipLogin}>
      <label for="loginInput">login</label>
      <input name="loginInput" type="text" bind:value={login} placeholder="e.g. user@email.com/username">
    </div>
    <div class="input-container" title={c.tipUri}>
      <label for="uriInput">website address</label>
      <input name="uriInput" type="url" bind:value={uri} placeholder="e.g. myspace.com">
    </div>
    <br/>
    <div class="checkbox">
      <label for=advOptsInput><span>advanced options<input name="advOptsInput" type="checkbox" bind:checked={advOpts}></span></label>
    </div>
    {#if advOpts}
      <br/>
      <div class="input-container" title={c.tipIndex}>
        <label for="indexInput">index</label>
        <input name="indexInput" type="number" min="0" steps="1" bind:value={index} on:keydown={blacklistDecimal} />
      </div>
      <div class="input-container" title={c.tipPassLen}>
        <label for="passLenInput">length</label>
        <input name="passLenInput" type="number" min="4" steps="1" bind:value={passLen} on:keydown={blacklistDecimal} />
      </div>
      <br/>
      <div class="input-container" spellcheck="false" title={c.tipPassFormat+`${charsetDefinitions}`}>
        <label for="childPassFormat">{c.childPassTerm.toLowerCase()} format</label>
        <input name="childPassFormat" type="text" bind:value={childPassFormat} on:keypress={handlePassFormatInput}>
      </div>
      <div class="input-container" spellcheck="false" title={c.tipCustomAlpha}>
        <label for="customAlphaInput">c: (custom alphabet)</label>
        <input name="customAlphaInput" type="text" bind:value={customAlpha} placeholder="e.g. abcd_!">
      </div>
      <br/>
    {/if}
    <br/>
    <br/>
    <div>
      <button on:click={handleGenerateClick}>
        generate {@html c.childPassHtml}
      </button>
      <div class="input-container" title={c.tipChildPass}>
        <textarea style="width:100%" placeholder="Copy me after generating!" bind:value={childPass} disabled />
      </div>
      <button disabled={childPass.length === 0} on:click={handleCopyClick}>
        copy
      </button>
    </div>
  {/if}
</div>

<style>
  /* used for tooltips to encompass the whole view of the input */
  div.input-container {
    max-width: 333px;
  }
  input {
    width: 100%;
    max-width: 333px;
  }
  .checkbox label {
    display: inline-block;
  }
  .checkbox input {
    width: auto;
    margin-left: 0.6rem;
  }
</style>
