<script>

// TODO divide this into Unlocker & Generator component for improved lazy loading
// Unlocker can be painted right away... but can await lazy load of needed argon2
// and any additional libs for Unlocker could maybe keep Unlocker from
// being blocked too long

import {
  afterUpdate
  , onMount
} from 'svelte'
import { deriveGeneratorPassword } from '@util/crypto/kdf'
import { loadDecryptSeed, isPlainMnemonicInStorage } from '@util/crypto/encryption'
import * as c from '@/constants.js'
import {
  needsSetup
  , disableAnnoyingMobileInputBugs
} from '@util/helper.js'
// derives a password from our params
import deriveSrsPass from '@util/srsPass/generator'
// provides necessities for helping transform generated bytes into a flexible outlined character sets
import {
  charsetDict,
  charsetDefinitions,
  dedupeChars,
  validatePassFormat,
} from '@util/srsPass/charsetter'
import Snackbar from '@component/Snackbar'
import Menu from '@component/Menu'
import { isAppUnlocked } from '@store/main'

const msg = {
  passInput: "Enter password here..."
  , loading:  "Generating..."
}

const regexHostname = `^([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]{0,61}[a-zA-Z0-9])(\.([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]{0,61}[a-zA-Z0-9]))*$`
let unlocking = false
  , generating = false
  , unlockPass = ''
  , salt = ''
  , pass = ""
  , childPass = ""
  , login = ""
  , uri = ""
  , advOpts = false
  , index = 0
  , passLen = 20
  , customAlpha = ''
  , childPassFormatDefault = '*'
  , childPassFormat = childPassFormatDefault
  , unlockPassInputDOM
  , showPass = false
  , showChildPass = false

charsetDict.c = customAlpha

onMount(() => unlockPassInputDOM = document.getElementById('unlockPassInput'))

afterUpdate(() => {
  disableAnnoyingMobileInputBugs()
})

function handleUnlockEnter(event) {
  if (event.key === "Enter") {
    event.preventDefault()
    handleUnlockClick()
  }
}

function handleCopyClick() {
  navigator.clipboard.writeText(childPass)
}

function handlePassFormatInput(event) {
  const { key } = event
  if (Object.keys(charsetDict).indexOf(key) < 0)
    return event.preventDefault()
  else if (key === 'c' && customAlpha.length === 0) {
    event.preventDefault()
    return alert(`You must define a custom alphabet in the input underneath, before you can use 'c' in the format!`)
  }
}

async function handleUnlockClick() {
  unlocking = true
  try {
    // add appropriate exceptions and handling thereof
    const saltProm = loadDecryptSeed(unlockPass)
    const passProm = deriveGeneratorPassword(unlockPass)
    unlockPass = ''
    salt = await saltProm
    pass = await passProm
  } catch (e) {
    const errorDict = {
      'Unsupported state or unable to authenticate data': `Incorrect ${c.passTerm.toLowerCase()} entered...`
    }
    const knownError = errorDict[e.message]
    if (knownError)
      alert(knownError)
    else
      console.error(e) || alert('Unhandled Error, check log and report!')
  } finally {
    unlocking = false
  }
}

async function handleGenerateClick() {
  const cpf = childPassFormat
  if (!validatePassFormat(cpf))
    return alert(`Invalid pass format... please check tooltips for valid characters by hovering over the ${childPassTerm} format input`)
  childPass = ""
  generating = true
  // uint8 array
  //let fmt = `${index}${uri}${login}`
  // index is omitted unless non-zero, to keep the salt from being too easily
  // identifiable by such a consistent marker in memory

  childPass = await deriveSrsPass(
    pass,
    salt,
    index,
    uri,
    login,
    passLen,
    cpf
  )
  generating = false
}

const blacklistDecimal = event =>
  event.keyCode === 190 && event.preventDefault()

const isEmpty = x => !x || x.length === 0
const isEmptyChildPass = () => isEmpty(childPass)

// input triggers
// NOTE update these if adding any new inputs to their respective cats
let baseInputs = [login, uri]
const baseInputsTrigger = () => baseInputs = baseInputs
$: login, uri, baseInputsTrigger()

let advInputs = [
  index,
  passLen,
  childPassFormat,
  customAlpha
]
const advInputsTrigger = () => advInputs = advInputs
$: index, passLen, childPassFormat, customAlpha, advInputsTrigger()

$: needsCredentials = isEmpty(pass) || isEmpty(salt)
$: needsCredentials ? isAppUnlocked.set(false) : isAppUnlocked.set(true)
$: index = Math.floor(index)
$: passLen = Math.floor(passLen)
$: customAlpha = dedupeChars(customAlpha)
$: charsetDict.c = customAlpha
$: if(customAlpha.length === 1 &&
  childPassFormat === childPassFormatDefault) childPassFormat = 'c'
$: {
  // NOTE sadly the input type can't be dynamic when there's two-way binding
  // else the unlockPassInput element would persist showPass settings inbetween
  //
  // TODO optional chaining with ?. would be nice to get workign here...
  const elem = document.getElementById('unlockPassInput')
  if (elem) elem.setAttribute('type', showPass ? 'text' : 'password')
}
$: unlocking && (showPass = false)
// clear password on any other input being changed
$: baseInputs, advInputs, !isEmptyChildPass() && (childPass = '')
$: login = login.trim()
$: uri = uri.trim()
</script>

<Menu />
<div>
  {#if needsCredentials}
    <h3>Usable offline & as PWA for extra security</h3>
    {#if unlocking}
      <p>Unlocking... please wait</p>
    {:else}
      <div title={c.tipUnlockPass}>
        <label for="unlockPassInput">Please enter your {@html c.passHtml} to begin!</label>
        <input autofocus={!needsSetup()} id="unlockPassInput" name="unlockPassInput" type="password" bind:value={unlockPass} disabled={unlocking} on:keypress={handleUnlockEnter}>
        <button on:click={handleUnlockClick} disabled={unlocking}>
          Unlock
        </button>
        <div class="checkbox">
          <label for=showUnlockPass><span>show password<input name="showUnlockPass" type="checkbox" bind:checked={showPass}></span></label>
        </div>
      </div>
    {/if}
  {:else}
    <p>Note: All inputs are cAsE sensitive!</p>
    <br/>
    <div class="input-container" title={c.tipLogin}>
      <label for="loginInput">login</label>
      <input name="loginInput" type="text" bind:value={login} placeholder="e.g. user@email.com/username">
    </div>
    <div class="input-container" title={c.tipUri}>
      <label for="uriInput">website address</label>
      <input name="uriInput" pattern={regexHostname} bind:value={uri} placeholder="e.g. wikipedia.org">
    </div>
    <br/>
    <div class="checkbox">
      <label for=advOptsInput><span>advanced options<input name="advOptsInput" type="checkbox" bind:checked={advOpts}></span></label>
    </div>
    {#if advOpts}
      <br/>
      <div class="input-container" title={c.tipIndex}>
        <label for="indexInput">index</label>
        <input name="indexInput" type="number" min="0" steps="1" bind:value={index} on:keydown={blacklistDecimal} />
      </div>
      <div class="input-container" title={c.tipPassLen}>
        <label for="passLenInput">length</label>
        <input name="passLenInput" type="number" min="4" steps="1" bind:value={passLen} on:keydown={blacklistDecimal} />
      </div>
      <br/>
      <div class="input-container" spellcheck="false" title={c.tipPassFormat+`${charsetDefinitions}`}>
        <label for="childPassFormat">{c.childPassTerm.toLowerCase()} format</label>
        <input name="childPassFormat" type="text" bind:value={childPassFormat} on:keypress={handlePassFormatInput}>
      </div>
      <div class="input-container" spellcheck="false" title={c.tipCustomAlpha}>
        <label for="customAlphaInput">c: (custom alphabet)</label>
        <input name="customAlphaInput" type="text" bind:value={customAlpha} placeholder="e.g. abcd_!">
      </div>
      <br/>
    {/if}
    <br/>
    <br/>
    <div>
      <button on:click={handleGenerateClick}>
        generate {@html c.childPassHtml}
      </button>
      <div class="input-container" title={c.tipChildPass} on:click={() => showChildPass = !showChildPass}>
        <textarea
          class="{ childPass.length > 0 && !showChildPass ? 'text-blur' : ''}"
          style="width:100%;"
          placeholder="Copy me after generating!"
          bind:value={childPass}
          readonly
        />
      </div>
      {#if navigator.clipboard}
      <button disabled={childPass.length === 0} on:click={handleCopyClick}>
        copy
      </button>
      {/if}
    </div>
    {#if isPlainMnemonicInStorage()}
      <Snackbar text={c.postVerifyAlert} />
    {/if}
  {/if}
</div>

<style>
  /* used for tooltips to encompass the whole view of the input */
  div.input-container {
    max-width: 333px;
  }
  input {
    width: 100%;
    max-width: 333px;
  }
  .checkbox label {
    display: inline-block;
  }
  .checkbox input {
    width: auto;
    margin-left: 0.6rem;
  }
</style>
