name: builder
on:
  push:
    branches:
    - master
    - develop
  pull_request:
    branches:
    - master
    - develop
jobs:
  build:
    name: svelte-build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: npm-ci
      run: npm ci
    - name: build
      run: npm run build
